service: serverless-example

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  region: eu-central-1
  environment:
    DB_NAME: ${ssm:/db-name~true}
    DB_USER: ${ssm:/db-username~true}
    DB_HOST: ${ssm:/db-host~true}
    DB_PORT: ${ssm:/db-port~true}
    DB_PASSWORD: ${ssm:/db-password~true}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  createArticle:
    handler: bin/create_article
    events:
      - httpApi:
          path: /articles
          method: post
  createAuthor:
    handler: bin/create_author
    events:
      - httpApi:
          path: /authors
          method: post
  getArticles:
    handler: bin/get_articles
    events:
      - httpApi:
          path: /articles
          method: get
  getAuthors:
    handler: bin/get_authors
    events:
      - httpApi:
          path: /authors
          method: get
